site_name: Peoria Rapid Response
site_url: https://peoriarr.org/

# Theme configuration
theme:
  logo: assets/prr-logo-new.svg
  name: material
  custom_dir: theme_overrides/
  features:
    - navigation.instant
    # - navigation.tabs
    # - navigation.sections
    - toc.integrate
    - navigation.tracking
  palette:
    - scheme: default
      primary: blue
      accent: indigo

# Homepage configuration
extra:
  homehtml:
    logo: assets/prr-logo-new.svg
    tagline_en: "Plug into Peoria's Rapid Response Network"
    tagline_es: "Conéctate a la Red de Respuesta Rápida de Peoria"
    buttons:
      - text_en: "Facebook"
        text_es: "Facebook"
        url: "https://www.facebook.com/profile.php?id=61572967701398"
      - text_en: "Email"
        text_es: "Email"
        url: "mailto:peoriarapidresponse@protonmail.com"
      - text_en: "BlueSky"
        text_es: "BlueSky"
        url: "https://bsky.app/profile/peoriarr.bsky.social"
      - text_en: "Mastodon"
        text_es: "Mastodon"
        url: "https://freeradical.zone/@peoriarr"
      - text_en: "About Us"
        text_es: ""
        url: "about"
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Español
      link: /es/
      lang: es

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - attr_list

# Plugin configuration
plugins:
  - search
  - social
  - minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true
